spring:
  datasource:
    url: jdbc:mysql://${DATABASE_URL:localhost}:${DB_PORT:3306}/${DB_NAME:integrator}?autoReconnect=true&useSSL=false&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
  h2:
    console:
      path: '/dbconsole'
      enabled: false
  flyway:
    enabled: true
